CREATE CONSTRAINT cstr_ruiro_id IF NOT EXISTS FOR (r:RuiRo) REQUIRE r.id IS UNIQUE;
CREATE CONSTRAINT cstr_kiemsoat_id IF NOT EXISTS FOR (k:KiemSoat) REQUIRE k.id IS UNIQUE;
CREATE CONSTRAINT cstr_sukienruiro_id IF NOT EXISTS FOR (s:SuKienRuiRo) REQUIRE s.id IS UNIQUE;